### ISSUE TITLE
The app registration is single tenant but it still fails due to missing tenant id

### ISSUE THREAD

**Issue by Adam-it** [pnp/action-cli-login#37]
So in noticed some strange behaviors in one of my demo flows https://github.com/Adam-it/demo1/actions/runs/7749116793/job/21133026261

My app is set to be single tenant

![image](https://github.com/pnp/action-cli-login/assets/58668583/3acdf2fb-2131-409b-96da-942fcd7a11be)

I used the following command to register it
```
m365 aad app add --name 'My CI/CD Application' --apisApplication 'https://microsoft.sharepoint-df.com/Sites.FullControl.All' --certificateFile ./CI-CD-Certificate.cer --certificateDisplayName 'CICD Certificate' --grantAdminConsent
```

and I use this step in my yaml

```
 - name: CLI for Microsoft 365 Login
        uses: pnp/action-cli-login@v2.2.4
        with:
          CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          APP_ID: ${{ secrets.APP_ID }}
```

but I still get an error that I need to specify the tenant Id which I think in case of single tenant app registration we should not do.

![image](https://github.com/pnp/action-cli-login/assets/58668583/50e71669-bf91-4b13-ae9a-fb2a24fdc360)

this is also something that we defined in the guidance 
https://pnp.github.io/cli-microsoft365/user-guide/github-actions

![image](https://github.com/pnp/action-cli-login/assets/58668583/7a56ac47-cde8-4f05-93d2-c9f870e9a51e)

am I missing something here or is this a bug 😉?
